Repository spherical-volume-rendering/svr-algorithm, pull requests merged in 2020-04, with the labels that each got.

#78 Enhancements and fixes
  matlab/polar-traversal/angular_hit.m
  matlab/polar-traversal/approximatelyEqual.m
  matlab/polar-traversal/polarCoordinateTraversal.m
  matlab/polar-traversal/polarCoordinateTraversalExample.m
  matlab/polar-traversal/polarCoordinateTraversalTest.m
  matlab/polar-traversal/radial_hit.m
Labels: enhancement

#79 [WIP] Implement updated angular hit, azimuthal hit, traversal phase to remove trigonometric, matrix calculations and cleanup.
  cpp/cython/CythonSVR.pyx
  cpp/cython/CythonSVR_test.py
  cpp/ray.h
  cpp/spherical_volume_rendering_util.cpp
  cpp/spherical_volume_rendering_util.h
  cpp/spherical_voxel_grid.h
  cpp/testing/CMakeLists.txt
  cpp/testing/spherical_volume_rendering_test.cpp
Labels: documentation, enhancement, testing

#80 Add simple spherical traversal tests.
  matlab/spherical-traversal/sphericalCoordinateTraversalTest.m
Labels: testing

#76 Chord length test
  matlab/polar-traversal/polarCoordinateTraversal.m
Labels: testing

#93 Update Cython tests.
  cpp/cython/CythonSVR_test.py
  cpp/cython/printTests.py
Labels: testing

#105 Small optimizations for the traversal algorithm.
  .gitignore
  cpp/spherical_volume_rendering_util.cpp
  cpp/testing/CMakeLists.txt
  cpp/testing/benchmarking.cpp
  cpp/testing/profiling.cpp
Labels: optimization

#103 Multiple updates; test passer
  matlab/spherical-traversal/SphericalCoordinateTraversalExample.m
  matlab/spherical-traversal/angular_hit.m
  matlab/spherical-traversal/azimuthal_hit.m
  matlab/spherical-traversal/sphericalCoordinateTraversal.m
  matlab/spherical-traversal/sphericalCoordinateTraversalTest.m
Labels: optimization

#111 Add namespaces, optimize Ray functions, add orthographic benchmark.
  cpp/ray.h
  cpp/spherical_volume_rendering_util.cpp
  cpp/spherical_volume_rendering_util.h
  cpp/spherical_voxel_grid.h
  cpp/testing/CMakeLists.txt
  cpp/testing/SVR_benchmarks.cpp
  cpp/testing/SVR_tests.cpp
  cpp/vec3.h
Labels: documentation, optimization

#114 Add -O3 optimization compiler arg, code clean up.
  cpp/cython/Cython_SVR.cpp
  cpp/cython/Cython_SVR.pyx
  cpp/cython/Cython_SVR_setup.py
  cpp/cython/Cython_SVR_tests.py
  cpp/spherical_volume_rendering_util.cpp
  cpp/spherical_volume_rendering_util.h
  cpp/spherical_voxel_grid.h
  cpp/testing/SVR_benchmarks.cpp
  cpp/testing/SVR_tests.cpp
Labels: documentation, optimization

#124 Add documentation to benchmarks.
  cpp/spherical_volume_rendering_util.cpp
  cpp/testing/SVR_benchmarks.cpp
Labels: documentation

#125 Orthographic ray trace benchmark.
  cpp/testing/SVR_benchmarks.cpp
Labels: testing

#128 Implement #126 tests in cpp, cython.
  .gitignore
  cpp/cython/cython_SVR_tests.py
  cpp/spherical_volume_rendering_util.cpp
  cpp/testing/SVR_benchmarks.cpp
  cpp/testing/SVR_tests.cpp
  cpp/testing/print_tests_script.py
  cpp/vec3.h
Labels: testing

#131 Simplify radialHit() logic.
  cpp/spherical_volume_rendering_util.cpp
  cpp/spherical_voxel_grid.h
  cpp/vec3.h
Labels: enhancement, optimization

#134 Reduce floating point calculations in angular, azimuthal hit.
  cpp/ray.h
  cpp/spherical_volume_rendering_util.cpp
  cpp/spherical_voxel_grid.h
  cpp/testing/SVR_tests.cpp
Labels: optimization

#135 Remove need of std::vector in radialHit(), only use ABS_EPSILON to determine FP equality.
  cpp/ray.h
  cpp/spherical_volume_rendering_util.cpp
  cpp/vec3.h
Labels: optimization

#136 Pre-initialize deltaRadii calculations.
  cpp/spherical_volume_rendering_util.cpp
  cpp/spherical_voxel_grid.h
  cpp/vec3.h
Labels: optimization

#138 Create algorithm template for CalculateVoxelID() to avoid returning a dummy value with adjacent_find.
  cpp/spherical_volume_rendering_util.cpp
Labels: enhancement

#141 Reduce radialHit() calculations.
  cpp/spherical_volume_rendering_util.cpp
  cpp/spherical_voxel_grid.h
Labels: optimization
